services:
  db:
    image: postgres:alpine
    restart: always
    shm_size: 128mb
    ports:
    - 5437:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: inf362
